site:
  title: "Lamb Cottage Caravan Park"
  description: "Award-winning adults-only caravan park in Cheshire"
  contact:
    phone: "01606 882302"
    email: "info@lambcottage.co.uk"
    address: "Lamb Cottage Caravan Park
Dalefords Lane
Whitegate
Nr. Northwich
Cheshire, CW8 2BN"
  social:
    facebook: "https://facebook.com/lambcottage"
    instagram: "https://instagram.com/lambcottage"