name = "lamb-cottage-20205-workers"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js"

# KV Namespace bindings
[[kv_namespaces]]
binding = "CONTENT_KV"
id = "60c75603f410405db23bca3438e6b383"
preview_id = "81fd92a660ce4f3292c51952f0ecb209"

[[kv_namespaces]]
binding = "IMAGES_KV"
id = "d1dbc062bcb843bbb49659c1527d0625"
preview_id = "c1404b234127419d802e68193a55d89f"

# R2 Bucket bindings
[[r2_buckets]]
binding = "IMAGES_R2"
bucket_name = "lamb-cottage-images"
preview_bucket_name = "lamb-cottage-images-preview"

# Environment variables for production
# Note: These should be configured in Cloudflare Pages dashboard
# JWT_SECRET = "your-production-jwt-secret"
# ADMIN_PASSWORD_HASH = "your-production-password-hash"
# NODE_ENV = "production"
# R2_PUBLIC_URL = "https://pub-{your-account-hash}.r2.dev/lamb-cottage-images"