name = "lamb-cottage-caravan-park"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables for production
# Note: These should be configured in Cloudflare Pages dashboard
# JWT_SECRET = "your-production-jwt-secret"
# ADMIN_PASSWORD_HASH = "your-production-password-hash"
# NODE_ENV = "production"