name = "lamb-cottage-caravan-park"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.production]
name = "lamb-cottage-caravan-park"

[env.production.vars]
NODE_ENV = "production"

# Pages configuration
[pages]
build_output_dir = "dist"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"
node_compat = true

# Environment variables for Pages
[pages.env_vars]
NODE_ENV = "production"
JWT_SECRET = "your-production-jwt-secret-key-change-this-to-a-secure-random-string"
ADMIN_PASSWORD_HASH = "$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi"